// GENERATED by scripts/build-holders.mjs — do not edit by hand.
//
// Derived by replaying every Transfer since deploy: no free API exposes a
// holder count for Cronos. Re-run the script to refresh it.

export type HolderSnapshot = {
  /** Addresses holding a non-zero balance, excluding the zero and burn addresses. */
  readonly count: number;
  /** Chain height the scan reached. */
  readonly block: number;
  /** When the scan ran, ISO 8601. */
  readonly takenAt: string;
  /** Transfer events replayed to produce it. */
  readonly transfers: number;
};

export const HOLDERS: HolderSnapshot = {
  count: 343,
  block: 95603066,
  takenAt: "2026-09-23T04:19:30.355Z",
  transfers: 21080,
};
