// GENERATED by scripts/build-holders.mjs — do not edit by hand.
//
// Derived by replaying every Transfer since deploy: no free API exposes a
// holder count for Cronos. Re-run the script to refresh it.

export type HolderSnapshot = {
  /** Addresses holding a non-zero balance, excluding the zero and burn addresses. */
  readonly count: number;
  /** Chain height the scan reached. */
  readonly block: number;
  /** When the scan ran, ISO 8601. */
  readonly takenAt: string;
  /** Transfer events replayed to produce it. */
  readonly transfers: number;
};

export const HOLDERS: HolderSnapshot = {
  count: 337,
  block: 95255911,
  takenAt: "2026-09-21T11:00:50.901Z",
  transfers: 16472,
};
