// GENERATED by scripts/build-assets.mjs — do not edit by hand.
//
// The 20 cat portraits, 4 skins x 5 power stages. Names, tags and blurbs are the
// artwork's own. Every file is 580x768 with the subject centred, so the
// generator can swap one for another without recomputing any offset.

export const SPRITE_CANVAS = { width: 580, height: 768 } as const;

export type SkinId = "ultcat" | "midnyte" | "frost" | "blaze";
export type StageId = "base" | "ssj1" | "ssj2" | "ssj3" | "maxed";

export interface Skin {
  id: SkinId;
  name: string;
  tag: string;
  blurb: string;
}

export interface Stage {
  id: StageId;
  name: string;
  short: string;
}

export const SKINS: readonly Skin[] = [
  { id: "ultcat", name: "ULT CAT", tag: "ORIGIN", blurb: "Gold ki. The first to MAXED." },
  { id: "midnyte", name: "MIDNYTE", tag: "STORM", blurb: "Blue lightning. Twin-blade ki." },
  { id: "frost", name: "FROST", tag: "ICE", blurb: "Ice ki. Cold, clean hits." },
  { id: "blaze", name: "BLAZE", tag: "INFERNO", blurb: "Red ki. Burn the skies." },
] as const;

/** Ordered weakest to strongest, the way the artwork's own power ladder runs. */
export const STAGES: readonly Stage[] = [
  { id: "base", name: "CAT", short: "CAT" },
  { id: "ssj1", name: "ULTCAT", short: "ULTCAT" },
  { id: "ssj2", name: "SUPER ULTCAT", short: "SUPER" },
  { id: "ssj3", name: "ULTRA CAT", short: "ULTRA" },
  { id: "maxed", name: "MAXED", short: "MAXED" },
] as const;

export function spriteUrl(skin: SkinId, stage: StageId): string {
  return `/cat/${skin}-${stage}.webp`;
}
